### ISSUE TITLE
error in downloading

### ISSUE THREAD

**Issue by phtephanx** [michaelnmmeyer/gutenberg#1]
When executing `gutenberg download "language:de"`, the following error occurs:

```
user:~/Documents/books$ gutenberg download "language:de"
gutenberg: updating catalog
Traceback (most recent call last):
  File "/usr/local/bin/gutenberg", line 843, in <module>
    cmd["func"](argv[2:])
  File "/usr/local/bin/gutenberg", line 794, in cmd_download
    Gutenberg().download(argv[0])
  File "/usr/local/bin/gutenberg", line 672, in __init__
    self.update_catalog()
  File "/usr/local/bin/gutenberg", line 678, in update_catalog
    for key, fp in iter_catalog(self.catalog_url):
  File "/usr/local/bin/gutenberg", line 657, in iter_catalog
    key = int(os.path.basename(os.path.dirname(tinfo.name)))
ValueError: invalid literal for int() with base 10: 'DELETE-52276'
```

Is the repository up-to-date with the current Gutenberg-website in general?

**Comment by michaelnmmeyer** [comment]
Thank you for the bug report.

This is corrected in the master branch.
